version: "3.1"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_local
    restart: always
    ports:
      - '3030:3000'
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Admin
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_local
    restart: always
    ports:
      - '8086:8086'
    networks:
      - grafana_network
      - chronograf_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=performance_testing
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Admin
  chronograf:
    image: chronograf:latest
    container_name: chronograf_local
    ports:
      - '127.0.0.1:8888:8888'
    networks:
      - chronograf_network
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=Admin

networks:
  grafana_network:
  chronograf_network:
volumes:
  grafana_data:
  influxdb_data:
  chronograf_data:
